### ISSUE TITLE
Jade and angular2 attribute syntax...

### ISSUE THREAD

**Issue by jdconley** [gabehayes/meteor-angular2-jade#1]
I am having trouble getting things to render correctly. Consider the following two snippets:

Jade:
```
form.register-form((ngSubmit)="save()" [ngFormModel]="contactForm" novalidate)
```

Yields:
```
<form (ngSubmit)="contactForm" novalidate class="register-form">
```

and Jade:
```
tr.loan-program-entry(*ngFor="#program of model.institution.loanPrograms; #i = index" [control-group]="loanPrograms" [model]="program" [index]="i")
```

Yields:
```
<tr *ngFor="i" class="loan-program-entry"></tr>
```

Any thoughts on how to get around this? Using Jade for my simpler handlebars-style views seems to work fine, but using the angular2 style attributes seems to be a no-go.

**Comment by jdconley** [comment]
I ended up de-sugaring everything to get it to work. So, these lines became:

```
form.register-form(on-ngSubmit="save()" bind-ngFormModel="contactForm" novalidate)
```

and

```
template(ngFor var-program bind-ngForOf="model.institution.loanPrograms" var-i="index")
    tr.loan-program-entry(bind-control-group="loanPrograms" bind-model="program" bind-index="i")
```

It's a bummer the jade compiler doesn't handle this valid syntax. I'll go file a bug over there...

**Comment by gabehayes** [comment]
Sorry for not getting back sooner. And yes, you are correct, I had ran into this problem with the jade compiler early on and wasn't able to find a workaround.

Glad to see you found a way to get it to work by using the quotes!

If you run across anything else that can patch this plugin, feel free to submit a PR.

**Comment by jdconley** [comment]
It would be helpful to add this information to the README.
